const tarotCards = [
  { name: "The Fool", chinese: "愚者", image: "./tarot-images/m00.jpg", upright: "新的开始，冒险精神，天真无邪", reversed: "鲁莽，冒险，愚蠢的决定" },
  { name: "The Magician", chinese: "魔术师", image: "./tarot-images/m01.jpg", upright: "创造力，技能，实现目标", reversed: "操纵，欺骗，技能被滥用" },
  { name: "The High Priestess", chinese: "女祭司", image: "./tarot-images/m02.jpg", upright: "直觉，神秘，内在智慧", reversed: "压抑直觉，秘密，疏离" },
  { name: "The Empress", chinese: "皇后", image: "./tarot-images/m03.jpg", upright: "丰饶，母性，创造力", reversed: "依赖，空虚，缺乏创造力" },
  { name: "The Emperor", chinese: "皇帝", image: "./tarot-images/m04.jpg", upright: "权威，结构，控制", reversed: "专制，僵化，缺乏纪律" },
  { name: "The Hierophant", chinese: "教皇", image: "./tarot-images/m05.jpg", upright: "传统，信仰，精神指导", reversed: "叛逆，创新，逃避传统" },
  { name: "The Lovers", chinese: "恋人", image: "./tarot-images/m06.jpg", upright: "爱情，和谐，关系", reversed: "不和，失衡，错误的选择" },
  { name: "The Chariot", chinese: "战车", image: "./tarot-images/m07.jpg", upright: "意志力，胜利，进步", reversed: "缺乏自制，失败，退缩" },
  { name: "Strength", chinese: "力量", image: "./tarot-images/m08.jpg", upright: "勇气，毅力，自我控制", reversed: "缺乏信心，弱点，自我怀疑" },
  { name: "The Hermit", chinese: "隐士", image: "./tarot-images/m09.jpg", upright: "内省，孤独，寻找真理", reversed: "孤立，悲观，逃避" },
  { name: "Wheel of Fortune", chinese: "命运之轮", image: "./tarot-images/m10.jpg", upright: "命运，转折，机遇", reversed: "反叛，厄运，抗拒变化" },
  { name: "Justice", chinese: "正义", image: "./tarot-images/m11.jpg", upright: "公正，真理，法律", reversed: "不公，偏见，失衡" },
  { name: "The Hanged Man", chinese: "倒吊人", image: "./tarot-images/m12.jpg", upright: "放弃，等待，新视角", reversed: "拖延，抗拒，固执" },
  { name: "Death", chinese: "死神", image: "./tarot-images/m13.jpg", upright: "结束，转型，新生", reversed: "停滞，痴迷，拒绝改变" },
  { name: "Temperance", chinese: "节制", image: "./tarot-images/m14.jpg", upright: "平衡，节制，耐心", reversed: "不平衡，极端，失去控制" },
  { name: "The Devil", chinese: "恶魔", image: "./tarot-images/m15.jpg", upright: "束缚，依赖，物质主义", reversed: "解放，觉醒，自由" },
  { name: "The Tower", chinese: "高塔", image: "./tarot-images/m16.jpg", upright: "突变，混乱，启示", reversed: "避免灾难，恐惧，延迟改变" },
  { name: "The Star", chinese: "星星", image: "./tarot-images/m17.jpg", upright: "希望，灵感，平静", reversed: "绝望，缺乏信心，冷漠" },
  { name: "The Moon", chinese: "月亮", image: "./tarot-images/m18.jpg", upright: "幻觉，恐惧，潜意识", reversed: "清晰，revelations，克服恐惧" },
  { name: "The Sun", chinese: "太阳", image: "./tarot-images/m19.jpg", upright: "快乐，成功，活力", reversed: "暂时的挫折，缺乏快乐" },
  { name: "Judgement", chinese: "审判", image: "./tarot-images/m20.jpg", upright: "重生，内在召唤，宽恕", reversed: "自我怀疑，拒绝召唤，内疚" },
  { name: "The World", chinese: "世界", image: "./tarot-images/m21.jpg", upright: "完成，成就，圆满", reversed: "延迟，缺乏完成，空虚" },
  { name: "Ace of Wands", chinese: "权杖Ace", image: "./tarot-images/w01.jpg", upright: "创意的萌芽，新的开始，灵感", reversed: "创意受阻，延迟，缺乏动力" },
  { name: "Two of Wands", chinese: "权杖二", image: "./tarot-images/w02.jpg", upright: "计划，决策，展望未来", reversed: "犹豫不决，缺乏规划，害怕冒险" },
  { name: "Three of Wands", chinese: "权杖三", image: "./tarot-images/w03.jpg", upright: "扩张，成长，前瞻布局", reversed: "延迟，挫折，计划受阻" },
  { name: "Four of Wands", chinese: "权杖四", image: "./tarot-images/w04.jpg", upright: "庆祝，稳定，家庭和谐", reversed: "不稳定，缺乏庆祝，关系紧张" },
  { name: "Five of Wands", chinese: "权杖五", image: "./tarot-images/w05.jpg", upright: "竞争，冲突，挑战", reversed: "逃避冲突，过度竞争，混乱" },
  { name: "Six of Wands", chinese: "权杖六", image: "./tarot-images/w06.jpg", upright: "胜利，SUCCESS，公众认可", reversed: "失败，缺乏认可，自大" },
  { name: "Seven of Wands", chinese: "权杖七", image: "./tarot-images/w07.jpg", upright: "坚持，防守，保护立场", reversed: "放弃，防御失败，立场动摇" },
  { name: "Eight of Wands", chinese: "权杖八", image: "./tarot-images/w08.jpg", upright: "快速进展，行动，消息到来", reversed: "延迟，阻碍，行动迟缓" },
  { name: "Nine of Wands", chinese: "权杖九", image: "./tarot-images/w09.jpg", upright: "坚持，韧性，最后防御", reversed: "疲惫，放弃，过度防御" },
  { name: "Ten of Wands", chinese: "权杖十", image: "./tarot-images/w10.jpg", upright: "责任，负担，承担过多", reversed: "逃避责任，负担过重，压力巨大" },
  { name: "Page of Wands", chinese: "权杖侍从", image: "./tarot-images/w11.jpg", upright: "探索，热情，新灵感", reversed: "缺乏热情，延迟，不切实际" },
  { name: "Knight of Wands", chinese: "权杖骑士", image: "./tarot-images/w12.jpg", upright: "行动，热情，冲动", reversed: "鲁莽，失败，缺乏方向" },
  { name: "Queen of Wands", chinese: "权杖皇后", image: "./tarot-images/w13.jpg", upright: "独立，自信，慷慨", reversed: "自我中心，缺乏自信，依赖" },
  { name: "King of Wands", chinese: "权杖国王", image: "./tarot-images/w14.jpg", upright: "领导，vision，创业者", reversed: "专制，冲动，缺乏远见" },
  { name: "Ace of Cups", chinese: "圣杯Ace", image: "./tarot-images/c01.jpg", upright: "新的感情，灵感，情感萌芽", reversed: "情感封闭，灵感枯竭，冷漠" },
  { name: "Two of Cups", chinese: "圣杯二", image: "./tarot-images/c02.jpg", upright: "爱情，合作关系，情感连接", reversed: "关系紧张，合作破裂，分离" },
  { name: "Three of Cups", chinese: "圣杯三", image: "./tarot-images/c03.jpg", upright: "庆祝，友谊，团队合作", reversed: "过度庆祝，社交疲劳，孤立" },
  { name: "Four of Cups", chinese: "圣杯四", image: "./tarot-images/c04.jpg", upright: "反思，内省，忽视机会", reversed: "觉醒，抓住机会，重新投入" },
  { name: "Five of Cups", chinese: "圣杯五", image: "./tarot-images/c05.jpg", upright: "失落，失望，悲伤", reversed: "接受现实，重新振作，向前看" },
  { name: "Six of Cups", chinese: "圣杯六", image: "./tarot-images/c06.jpg", upright: "回忆，童年，纯真", reversed: "沉溺过去，无法前进，怀旧" },
  { name: "Seven of Cups", chinese: "圣杯七", image: "./tarot-images/c07.jpg", upright: "选择，幻想，机会", reversed: "现实，清晰，避免幻想" },
  { name: "Eight of Cups", chinese: "圣杯八", image: "./tarot-images/c08.jpg", upright: "离开，放弃，寻求更深意义", reversed: "固守，拖延，不愿放手" },
  { name: "Nine of Cups", chinese: "圣杯九", image: "./tarot-images/c09.jpg", upright: "满足，愿望实现，幸福", reversed: "不满，过度消费，空虚" },
  { name: "Ten of Cups", chinese: "圣杯十", image: "./tarot-images/c10.jpg", upright: "家庭幸福，和谐，情感满足", reversed: "家庭问题，分离，情感失落" },
  { name: "Page of Cups", chinese: "圣杯侍从", image: "./tarot-images/c11.jpg", upright: "创意，灵感，新情感", reversed: "情绪不稳定，缺乏创意，退缩" },
  { name: "Knight of Cups", chinese: "圣杯骑士", image: "./tarot-images/c12.jpg", upright: "浪漫，追求，梦想", reversed: "幻想破灭，情感操纵，逃避" },
  { name: "Queen of Cups", chinese: "圣杯皇后", image: "./tarot-images/c13.jpg", upright: "同情，直觉，情感支持", reversed: "情绪化，自我牺牲，依赖" },
  { name: "King of Cups", chinese: "圣杯国王", image: "./tarot-images/c14.jpg", upright: "情绪平衡，控制，成熟", reversed: "情绪失控，压抑，操纵" },
  { name: "Ace of Swords", chinese: "宝剑Ace", image: "./tarot-images/s01.jpg", upright: "清晰，突破，新想法", reversed: "混乱，误解，信息不全" },
  { name: "Two of Swords", chinese: "宝剑二", image: "./tarot-images/s02.jpg", upright: "平衡，中立，避免冲突", reversed: "不平衡，欺骗，被迫选择" },
  { name: "Three of Swords", chinese: "宝剑三", image: "./tarot-images/s03.jpg", upright: "心碎，悲伤，失落", reversed: "愈合，接受，原谅" },
  { name: "Four of Swords", chinese: "宝剑四", image: "./tarot-images/s04.jpg", upright: "休息，恢复，冥想", reversed: "疲惫，无法休息，过度思考" },
  { name: "Five of Swords", chinese: "宝剑五", image: "./tarot-images/s05.jpg", upright: "冲突，失败，取胜代价", reversed: "和解，避免冲突，宽恕" },
  { name: "Six of Swords", chinese: "宝剑六", image: "./tarot-images/s06.jpg", upright: "过渡，离开，疗愈之旅", reversed: "停滞，无法离开，反复困扰" },
  { name: "Seven of Swords", chinese: "宝剑七", image: "./tarot-images/s07.jpg", upright: "欺骗，偷窃，撤离", reversed: "面对现实，承担责任，诚实" },
  { name: "Eight of Swords", chinese: "宝剑八", image: "./tarot-images/s08.jpg", upright: "被困，限制，自我束缚", reversed: "解放，突破，自由" },
  { name: "Nine of Swords", chinese: "宝剑九", image: "./tarot-images/s09.jpg", upright: "焦虑，噩梦，恐惧", reversed: "缓解，面对恐惧，寻求帮助" },
  { name: "Ten of Swords", chinese: "宝剑十", image: "./tarot-images/s10.jpg", upright: "痛苦，结束，最低点", reversed: "重生，从最低点反弹，希望" },
  { name: "Page of Swords", chinese: "宝剑侍从", image: "./tarot-images/s11.jpg", upright: "新想法，好奇心，消息", reversed: "缺乏方向，欺骗，误解" },
  { name: "Knight of Swords", chinese: "宝剑骑士", image: "./tarot-images/s12.jpg", upright: "快速行动，雄心，冲动", reversed: "鲁莽，失败，缺乏判断" },
  { name: "Queen of Swords", chinese: "宝剑皇后", image: "./tarot-images/s13.jpg", upright: "独立，清晰，洞察", reversed: "冷漠，刻薄，情感隔离" },
  { name: "King of Swords", chinese: "宝剑国王", image: "./tarot-images/s14.jpg", upright: "权威，理性，法律", reversed: "滥用权力，冷酷，偏执" },
  { name: "Ace of Pentacles", chinese: " coins Ace", image: "./tarot-images/p01.jpg", upright: "新机会，物质潜力，繁荣", reversed: "错失机会，资源不足，延迟" },
  { name: "Two of Pentacles", chinese: " coins二", image: "./tarot-images/p02.jpg", upright: "平衡，灵活性，多任务", reversed: "失衡，混乱，无法适应" },
  { name: "Three of Pentacles", chinese: " coins三", image: "./tarot-images/p03.jpg", upright: "合作，团队，技能", reversed: "缺乏合作，沟通不畅，冲突" },
  { name: "Four of Pentacles", chinese: " coins四", image: "./tarot-images/p04.jpg", upright: "保守，储蓄，控制", reversed: "挥霍，控制欲过强，财务问题" },
  { name: "Five of Pentacles", chinese: " coins五", image: "./tarot-images/p05.jpg", upright: "财务困难，匮乏，孤立", reversed: "恢复，援助，希望" },
  { name: "Six of Pentacles", chinese: " coins六", image: "./tarot-images/p06.jpg", upright: "慷慨，慈善，财务分享", reversed: "贪婪，接受帮助，不平衡" },
  { name: "Seven of Pentacles", chinese: " coins七", image: "./tarot-images/p07.jpg", upright: "耐心，长期投资，评估", reversed: "不耐烦，短视，投资失败" },
  { name: "Eight of Pentacles", chinese: " coins八", image: "./tarot-images/p08.jpg", upright: "勤奋，专注，技能提升", reversed: "忽视，缺乏专注，低质量" },
  { name: "Nine of Pentacles", chinese: " coins九", image: "./tarot-images/p09.jpg", upright: "自足，独立，成功", reversed: "依赖，财务问题，自满" },
  { name: "Ten of Pentacles", chinese: " coins十", image: "./tarot-images/p10.jpg", upright: "财富，遗产，长期稳定", reversed: "财务不稳定，家庭问题，失败" },
  { name: "Page of Pentacles", chinese: " coins侍从", image: "./tarot-images/p11.jpg", upright: "新机会，学习，务实", reversed: "错失机会，缺乏务实，拖延" },
  { name: "Knight of Pentacles", chinese: " coins骑士", image: "./tarot-images/p12.jpg", upright: "努力，可靠，务实", reversed: "固执，缺乏创造力，拖延" },
  { name: "Queen of Pentacles", chinese: " coins皇后", image: "./tarot-images/p13.jpg", upright: "照顾，丰饶，提供者", reversed: "自恋，忽视自己，财务问题" },
  { name: "King of Pentacles", chinese: " coins国王", image: "./tarot-images/p14.jpg", upright: "财富，商业，领导", reversed: "贪婪，控制，财务不稳定" }
];
